service: list-tweets
frameworkVersion: ">=1.28.0 <2.0.0"
provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  stage: dev
  apiKeys:
    - free:
        - ${self:provider.stage}-harrietryderblog
  usagePlan:
    - free:
        quota:
          limit: 5000
          offset: 2
          period: MONTH
        throttle:
          burstLimit: 200
          rateLimit: 100

custom:
  stage: ${opt:stage, self:provider.stage}

  package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  tweets:
    handler: bin/tweets
    environment:
      STAGE: ${self:custom.stage}
      TWITTER_API_KEY: ${env:TWITTER_API_KEY}
      TWITTER_SECRET_KEY: ${env:TWITTER_SECRET_KEY}
    events:
      - http:
          path: /tweets
          method: get
          cors: true
          private: true
